### PR TITLE
Update Code of Conduct

### PR DESCRIPTION
**Pull request by pherterich**
Deleted the Portuguese one and slightly adjusted the English text to reflect the CERN study group in there

### CODE REVIEW

**Comment by RaoOfPhysics** [comment]
@ibab, @betatim: I have no idea how to cherrypick the relevant commits. :P HALP PLS.

**Comment by pherterich** [comment]
Me is sorry and will figure out and write guidelines on how to make proper PRs soon...

**Comment by betatim** [comment]
Can you briefly explain what you did @pherterich? It looks like you made a few edits in your repository, then made a PR to your own repository, merged them, and then made a PR to this fork? I don't think there is anything wrong with merging this as it is. The only drawback is that it clutters up the history a bit.

What I would do is to "squash" these commits into one. Then the history of this fork will look pretty. On your local copy of the repository do the following (after making a backup copy):

```
# get all the latest changes from your github fork
$ git fetch origin
# apply them to your local copy
$ git merge origin/master
# look at the history, this should show your last four commits and two more
$ git log -6
# get ready to squash!
$ git rebase -i HEAD~4
```

that last command will open an editor listing your four commits. Replace the `pick` infront of each the last three with `squash`, save and exit the editor. You'll get a new editor which shows all four commit messages. This is the commit message for your new commit, so edit them down to one message. Save and exit. Now do `git push --force` which is definitely in the "danger zone" of strong git-fu.

:rotating_light: don't get in the habit of using `--force` :rotating_light:

After all this if you check back on this page we should see just one commit in this pull request.

Let me know if there is something that isn't clear.

ps. if you don't feel like levelling up your git-fu today we can find a different solution as well

**Comment by pherterich** [comment]
I'm not doing command line -git, not sure if I will manage to teach myself today. But I can do it again in a hacky way.

**Comment by RaoOfPhysics** [comment]
@betatim teaching @pherterich to fish!

**Comment by RaoOfPhysics** [comment]
Pls to update and merge soon! I want to make a new event for this Friday and don't want to confuse you further by adding more commits for you to merge/rebase. :P

**Comment by jacquerie** [comment]
I guess I could act as the git elf of this repo and open another PR with the commits squashed?

**Comment by pherterich** [comment]
@jacquerie that would be lovely. I installed git and I did _something_ in my command line but I think this needs some more time on a weekend for me to figure out properly.

**Comment by RaoOfPhysics** [comment]
@jacquerie: Or you can pop over to @pherterich's office and help her do it? :D

**Comment by RaoOfPhysics** [comment]
Or what @pherterich said. :)

**Comment by pherterich** [comment]
Closing this one as it was fixed by #30

**Pull request closed without merging**
